version: '3.2'

services:

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    restart: "unless-stopped"
    environment: 
      - PORT=3000
      - SQLITE_DB=./sqlite.db
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.project_board_backend.rule=Host(`api.projectboard.vakedomen.ml`)
      - traefik.http.routers.project_board_backend.entrypoints=websecure
      - traefik.http.routers.project_board_backend.tls.certresolver=le

  frontend:
    container_name: porject_board
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.frontend
    restart: "unless-stopped"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.project_board.rule=Host(`projectboard.vakedomen.ml`)
      - traefik.http.routers.project_board.entrypoints=websecure
      - traefik.http.routers.project_board.tls.certresolver=le


networks:
  proxy:
    external: true
